#!/usr/bin/env python3
"""
Premium Account Warming Script v1 — 2026-04-17
Warms aged Reddit accounts with existing history through AdsPower browser profiles.

Key differences from regular warm.py:
- No browse-only phase gate (Phase 1 = IP acclimation with upvotes)
- Persona-aware commenting (comments pre-generated by LLM to match account voice)
- Mix of top-level and reply comments (40/60 split)
- Shorter sessions (25 min active + 20 min idle = 45 min)
- Targets account's historical subreddits, not defaults

Usage:
    python3 warm-premium.py <cdp_url> <username> <phase> \\
        --subreddits "AmItheAsshole,StardewValley,anime" \\
        [--comment-plan /path/to/plan.json]

Comment Plan JSON:
    [
        {
            "post_url": "https://www.reddit.com/r/.../comments/...",
            "comment": "The persona-matched comment text",
            "subreddit": "AmItheAsshole",
            "reply_to_comment": false
        }
    ]
"""

import asyncio
import json
import os
import random
import sys
import time
from datetime import datetime

try:
    from playwright.async_api import async_playwright
except ImportError:
    print(json.dumps({"success": False, "error": "playwright not installed"}))
    sys.exit(1)


# ─── Bandwidth Tracking ──────────────────────────────────────────────────────

class BandwidthTracker:
    """Track bytes sent/received via CDP Network events.
    Also handles media blocking on the SAME CDP session (issue #3 fix)."""
    def __init__(self):
        self.bytes_received = 0
        self.bytes_sent = 0
        self.request_count = 0
        self._cdp = None

    async def start(self, page, block_media=True):
        try:
            self._cdp = await page.context.new_cdp_session(page)
            await self._cdp.send("Network.enable")
            self._cdp.on("Network.dataReceived", self._on_data_received)
            self._cdp.on("Network.requestWillBeSent", self._on_request_sent)
            
            # Block images/video on the SAME CDP session (must share Network.enable)
            if block_media:
                await self._cdp.send("Network.setBlockedURLs", {
                    "urls": [
                        "*.jpg", "*.jpeg", "*.png", "*.gif", "*.webp", "*.svg", "*.ico",
                        "*.mp4", "*.webm", "*.m3u8", "*.ts", "*.avi", "*.mov",
                        "*.mp3", "*.ogg", "*.wav",
                        "*preview.redd.it/*", "*i.redd.it/*", "*v.redd.it/*",
                        "*external-preview.redd.it/*", "*thumbs.redditmedia.com/*",
                        "*i.imgur.com/*", "*imgur.com/*.jpg", "*imgur.com/*.png",
                    ]
                })
                print("[bandwidth] Blocked images/video loading", file=sys.stderr)
        except Exception as e:
            print(f"[bandwidth] Failed to start CDP tracking: {e}", file=sys.stderr)

    def _on_data_received(self, params):
        self.bytes_received += params.get("encodedDataLength", 0)

    def _on_request_sent(self, params):
        self.request_count += 1
        req = params.get("request", {})
        headers_text = "\r\n".join(f"{k}: {v}" for k, v in req.get("headers", {}).items())
        self.bytes_sent += len(headers_text.encode()) + len(req.get("postData", "").encode())

    def summary(self):
        return {
            "bytes_received": self.bytes_received,
            "bytes_sent": self.bytes_sent,
            "bytes_total": self.bytes_received + self.bytes_sent,
            "mb_received": round(self.bytes_received / (1024 * 1024), 2),
            "mb_sent": round(self.bytes_sent / (1024 * 1024), 2),
            "mb_total": round((self.bytes_received + self.bytes_sent) / (1024 * 1024), 2),
            "request_count": self.request_count,
        }


# ─── Session Timing ──────────────────────────────────────────────────────────

ACTIVE_BROWSE_MINUTES = 25
IDLE_MINUTES = 20
TOTAL_SESSION_SECONDS = (ACTIVE_BROWSE_MINUTES + IDLE_MINUTES) * 60  # 45 min


# ─── Phase Configuration ─────────────────────────────────────────────────────

PHASE_CONFIG = {
    1: {
        # IP Acclimation — browse + upvote, no comments
        "upvotes": (8, 12),
        "downvotes": (1, 3),
        "comments": 0,
        "posts_to_read": (6, 10),
        "saves": (1, 3),
        "top_level_ratio": 0,
    },
    2: {
        # Voice Reactivation — replies ONLY, deep in threads (never top-level during warming)
        "upvotes": (8, 15),
        "downvotes": (2, 4),
        "comments": (2, 4),
        "posts_to_read": (6, 10),
        "saves": (1, 3),
        "top_level_ratio": 0.0,  # 0% top-level during warming — all replies deep in threads
    },
    3: {
        # Operational — can mix top-level and replies
        "upvotes": (10, 18),
        "downvotes": (2, 5),
        "comments": (4, 6),
        "posts_to_read": (8, 12),
        "saves": (2, 4),
        "top_level_ratio": 0.4,  # 40% top-level only after fully operational
    },
}

PAGE_TIMEOUT = 20000
CAPTCHA_STRINGS = [
    "please verify", "captcha", "are you a robot", "challenge",
    "press and hold", "human verification", "blocked",
]


# ─── CAPTCHA Detection ──────────────────────────────────────────────────────

async def detect_captcha(page):
    try:
        text = (await page.text_content("body") or "").strip()
        text_lower = text.lower()
        if len(text) < 200:
            for sig in CAPTCHA_STRINGS:
                if sig in text_lower:
                    return True
            if len(text) < 30:
                return True
        title = (await page.title() or "").lower()
        if any(sig in title for sig in ["captcha", "blocked", "verify", "robot"]):
            return True
    except:
        pass
    return False


# ─── Helpers ─────────────────────────────────────────────────────────────────

def pick_range(r):
    if isinstance(r, tuple):
        return random.randint(r[0], r[1])
    return r


async def human_delay(min_s=1.0, max_s=3.0):
    await asyncio.sleep(random.uniform(min_s, max_s))


async def human_scroll(page, scrolls=3):
    for _ in range(scrolls):
        amount = random.randint(250, 600)
        await page.mouse.wheel(0, amount)
        await human_delay(1.5, 4.0)


async def type_human(page, text):
    """Type like a human — variable speed, pauses at punctuation."""
    for char in text:
        await page.keyboard.type(char, delay=0)
        delay = random.uniform(0.04, 0.10)
        if char in '.!?,;:':
            delay += random.uniform(0.15, 0.4)
        elif char == ' ':
            delay += random.uniform(0.03, 0.10)
        elif random.random() < 0.05:
            delay += random.uniform(0.1, 0.25)
        await asyncio.sleep(delay)


# ─── Core Actions ────────────────────────────────────────────────────────────

async def browse_and_collect_posts(page, subreddits, num_posts):
    """Browse account's historical subs and collect post data."""
    posts = []
    subs_to_browse = random.sample(subreddits, min(len(subreddits), 5))

    for sub in subs_to_browse:
        try:
            sort = random.choice(["hot", "hot", "rising", "new"])  # Bias toward hot
            url = f"https://www.reddit.com/r/{sub}/{sort}/"
            await page.goto(url, wait_until="domcontentloaded", timeout=PAGE_TIMEOUT)

            if await detect_captcha(page):
                continue

            await human_delay(2, 4)
            await human_scroll(page, random.randint(3, 6))

            post_links = await page.evaluate("""() => {
                const links = document.querySelectorAll('a[slot="full-post-link"]');
                return Array.from(links).slice(0, 15).map(a => {
                    const article = a.closest('article') || a.closest('shreddit-post');
                    let score = 0;
                    let numComments = 0;
                    let hasText = false;

                    if (article) {
                        const scoreEl = article.querySelector('[score]');
                        if (scoreEl) score = parseInt(scoreEl.getAttribute('score') || '0');
                        const commentEl = article.querySelector('a[href*="comments"]');
                        if (commentEl) {
                            const match = commentEl.textContent.match(/(\\d+)/);
                            if (match) numComments = parseInt(match[1]);
                        }
                        const postBody = article.querySelector('[slot="text-body"]');
                        hasText = !!(postBody && postBody.textContent.trim().length > 20);
                    }

                    return {
                        url: a.href,
                        title: a.textContent.trim().substring(0, 200),
                        score: score,
                        num_comments: numComments,
                        has_text_content: hasText,
                    };
                });
            }""")

            for pl in post_links:
                if pl['url'] and '/comments/' in pl['url']:
                    posts.append({**pl, 'subreddit': sub})
        except Exception:
            pass

    random.shuffle(posts)
    return posts[:num_posts + 5]


async def read_post(page, post_url):
    """Navigate to a post, scroll through it naturally. Spend real time reading."""
    try:
        await page.goto(post_url, wait_until="domcontentloaded", timeout=PAGE_TIMEOUT)
        if await detect_captcha(page):
            return False
        # Actually read the post — spend 8-20 seconds before scrolling
        await human_delay(8, 20)
        # Scroll through comments slowly
        await human_scroll(page, random.randint(3, 7))
        # Pause on a comment like reading it
        await human_delay(5, 12)
        # Maybe scroll a bit more
        if random.random() < 0.5:
            await human_scroll(page, random.randint(2, 4))
            await human_delay(4, 8)
        return True
    except Exception:
        return False


async def browse_feed(page, subreddit):
    """Browse a subreddit feed naturally without clicking into posts.
    Simulates scrolling through the feed reading titles."""
    try:
        sort = random.choice(["hot", "new", "rising"])
        await page.goto(f"https://www.reddit.com/r/{subreddit}/{sort}/",
                       wait_until="domcontentloaded", timeout=PAGE_TIMEOUT)
        if await detect_captcha(page):
            return
        await human_delay(3, 6)
        # Slow scroll through the feed
        for _ in range(random.randint(4, 8)):
            await page.mouse.wheel(0, random.randint(200, 500))
            await human_delay(3, 8)  # Pause like reading titles
        await human_delay(2, 5)
    except Exception:
        pass


async def upvote_post(page):
    try:
        upvote_btn = page.get_by_role("button", name="Upvote").first
        if await upvote_btn.count() > 0:
            pressed = await upvote_btn.get_attribute("aria-pressed")
            if pressed != "true":
                await upvote_btn.click()
                await human_delay(0.5, 1.5)
                return True
    except Exception:
        pass
    return False


async def downvote_post(page):
    try:
        downvote_btn = page.get_by_role("button", name="Downvote").first
        if await downvote_btn.count() > 0:
            pressed = await downvote_btn.get_attribute("aria-pressed")
            if pressed != "true":
                await downvote_btn.click()
                await human_delay(0.5, 1.5)
                return True
    except Exception:
        pass
    return False


async def save_post(page):
    try:
        save_btn = page.get_by_role("button", name="Save")
        if await save_btn.count() > 0:
            await save_btn.first.click()
            await human_delay(0.5, 1.0)
            return True
    except Exception:
        pass
    return False


async def post_top_level_comment(page, text):
    """Post a top-level comment on the current post page."""
    try:
        # Dismiss any stale modals
        discard = page.get_by_role("button", name="Discard")
        if await discard.count() > 0:
            await discard.first.click()
            await human_delay(1, 2)

        composer_host = page.locator("comment-composer-host")
        if await composer_host.count() == 0:
            return False

        await composer_host.first.scroll_into_view_if_needed()
        await human_delay(0.5, 1.0)
        await composer_host.first.click()
        await human_delay(1.5, 3.0)

        editor = page.locator('div[contenteditable="true"]')
        visible_editors = []
        for i in range(await editor.count()):
            if await editor.nth(i).is_visible():
                box = await editor.nth(i).bounding_box()
                if box and box['width'] > 100:
                    visible_editors.append(editor.nth(i))

        if not visible_editors:
            return False

        target_editor = visible_editors[0]
        await target_editor.click()
        await human_delay(0.5, 1.0)
        await type_human(page, text)
        await human_delay(1.0, 2.0)

        submit_btn = await page.evaluate("""() => {
            const composers = document.querySelectorAll('shreddit-composer');
            for (const c of composers) {
                const btn = c.querySelector('button[slot="submit-button"]');
                if (btn) {
                    const r = btn.getBoundingClientRect();
                    if (r.width > 0) return {x: r.x + r.width/2, y: r.y + r.height/2};
                }
            }
            return null;
        }""")

        if not submit_btn:
            return False

        await page.mouse.click(submit_btn['x'], submit_btn['y'])
        await human_delay(3, 5)
        return True
    except Exception:
        return False


async def reply_to_comment(page, text, target_author=None):
    """Reply to an existing comment on the current post page.
    
    If target_author is provided, finds that user's comment and replies to it.
    This ensures the LLM-generated reply matches the comment it's attached to.
    Falls back to picking a mid-thread comment (not top, not buried) if author not found.
    """
    try:
        # Find reply buttons with their associated comment author
        reply_buttons = await page.evaluate("""(targetAuthor) => {
            const comments = document.querySelectorAll('shreddit-comment');
            const buttons = [];
            for (let i = 0; i < Math.min(comments.length, 20); i++) {
                const c = comments[i];
                if (c.offsetHeight < 20) continue;
                
                // Get comment author
                const author = c.getAttribute('author') || '';
                
                // Get depth (nested replies are deeper)
                const depth = parseInt(c.getAttribute('depth') || '0');
                
                const replyBtn = c.querySelector('button[aria-label*="Reply"], button[commandfor="comment-composer-host"]');
                if (replyBtn) {
                    const r = replyBtn.getBoundingClientRect();
                    if (r.width > 0 && r.height > 0) {
                        buttons.push({
                            index: i,
                            author: author,
                            depth: depth,
                            x: r.x + r.width / 2,
                            y: r.y + r.height / 2,
                            isTarget: targetAuthor && author.toLowerCase() === targetAuthor.toLowerCase(),
                        });
                    }
                }
            }
            return buttons;
        }""", target_author or "")
        
        if not reply_buttons:
            return False
        
        # Priority 1: Match target author (the comment our reply was written for)
        target = None
        target_matches = [b for b in reply_buttons if b.get("isTarget")]
        if target_matches:
            target = target_matches[0]
        else:
            # Priority 2: Pick a mid-depth comment (not top-level, not deeply buried)
            # Skip the first comment (most visible), prefer depth >= 1
            deep_candidates = [b for b in reply_buttons if b["depth"] >= 1]
            mid_candidates = reply_buttons[2:] if len(reply_buttons) > 3 else reply_buttons[1:]
            candidates = deep_candidates if deep_candidates else mid_candidates
            if not candidates:
                candidates = reply_buttons
            target = random.choice(candidates)
        
        # Scroll the reply button into view
        await page.mouse.wheel(0, max(0, target['y'] - 400))
        await human_delay(1, 2)
        
        # Click reply
        await page.mouse.click(target['x'], target['y'])
        await human_delay(1.5, 3.0)
        
        # Find the newly opened reply editor
        editor = page.locator('div[contenteditable="true"]')
        visible_editors = []
        for i in range(await editor.count()):
            if await editor.nth(i).is_visible():
                box = await editor.nth(i).bounding_box()
                if box and box['width'] > 80:
                    visible_editors.append(editor.nth(i))
        
        if not visible_editors:
            return False
        
        # Use the last visible editor (most likely the reply box that just opened)
        target_editor = visible_editors[-1]
        await target_editor.click()
        await human_delay(0.5, 1.0)
        await type_human(page, text)
        await human_delay(1.0, 2.0)
        
        # Find and click submit in the reply composer
        submit_btn = await page.evaluate("""() => {
            const composers = document.querySelectorAll('shreddit-composer');
            let lastBtn = null;
            for (const c of composers) {
                const btn = c.querySelector('button[slot="submit-button"]');
                if (btn) {
                    const r = btn.getBoundingClientRect();
                    if (r.width > 0) lastBtn = {x: r.x + r.width/2, y: r.y + r.height/2};
                }
            }
            return lastBtn;
        }""")
        
        if not submit_btn:
            return False
        
        await page.mouse.click(submit_btn['x'], submit_btn['y'])
        await human_delay(3, 5)
        return True
    except Exception:
        return False


async def verify_comment_posted(page, post_url, username):
    """Verify a comment wasn't auto-removed by revisiting the post.
    Returns True if the user's comment is visible, False if removed/missing."""
    try:
        await page.goto(post_url, wait_until="domcontentloaded", timeout=PAGE_TIMEOUT)
        await human_delay(2, 4)
        await human_scroll(page, 2)
        
        # Check if our username appears in the comments
        found = await page.evaluate("""(username) => {
            const comments = document.querySelectorAll('shreddit-comment');
            for (const c of comments) {
                const author = (c.getAttribute('author') || '').toLowerCase();
                if (author === username.toLowerCase()) return true;
            }
            return false;
        }""", username)
        
        return found
    except Exception:
        return True  # Assume OK if we can't check (don't false-positive)


# ─── Main Session ────────────────────────────────────────────────────────────

async def run_premium_warming(cdp_url, username, phase, subreddits, comment_plan=None):
    config = PHASE_CONFIG[phase]

    # No comments in Phase 1 regardless
    if phase < 2:
        comment_plan = None

    results = {
        "username": username,
        "phase": phase,
        "timestamp": datetime.now().isoformat(),
        "posts_read": 0,
        "upvotes": 0,
        "downvotes": 0,
        "comments_posted": [],
        "comments_skipped": 0,
        "removed_comments": 0,
        "saves": 0,
        "errors": [],
        "captcha_hit": False,
        "success": True,
        "bandwidth": {},
        "active_minutes": 0,
        "idle_minutes": 0,
    }

    pw = await async_playwright().start()
    browser = None
    bw = None  # Initialize before try so finally block doesn't throw NameError

    try:
        browser = await pw.chromium.connect_over_cdp(cdp_url)
        ctx = browser.contexts[0]
        page = ctx.pages[0] if ctx.pages else await ctx.new_page()

        bw = BandwidthTracker()
        await bw.start(page, block_media=True)  # Tracking + media blocking on same CDP session
        session_start = time.time()

        # Homepage check
        await page.goto("https://www.reddit.com/", wait_until="domcontentloaded", timeout=PAGE_TIMEOUT)
        if await detect_captcha(page):
            results["captcha_hit"] = True
            results["success"] = False
            results["errors"].append("CAPTCHA detected on homepage — aborting")
            print(json.dumps(results, indent=2))
            return results

        await human_delay(2, 4)

        # Login verification — check if account is actually logged in
        logged_in = await page.evaluate("""() => {
            // Check for logged-in indicators
            const loginBtn = document.querySelector('a[href*="login"], button[id*="login"]');
            const userMenu = document.querySelector('faceplate-tracker[noun="user_menu"]');
            const avatar = document.querySelector('faceplate-tracker[source="nav"] img[alt*="avatar"], img[alt="User Avatar"]');
            const profileLink = document.querySelector('a[href*="/user/"]');
            // If login button is visible and no user menu/avatar, we're logged out
            if (loginBtn && !userMenu && !avatar) return false;
            // If we see user menu or avatar, we're logged in
            if (userMenu || avatar || profileLink) return true;
            // Ambiguous — check for the expandable user drawer
            const drawer = document.querySelector('#USER_DRAWER_ID, shreddit-async-loader[bundlename="user_drawer"]');
            return !!drawer;
        }""")
        
        if not logged_in:
            results["success"] = False
            results["errors"].append("NOT LOGGED IN — session invalid, cookies may have expired")
            print(json.dumps(results, indent=2))
            return results
        
        print(f"[auth] Login verified for {username}", file=sys.stderr)

        # ── Browse + upvote/downvote/save ────────────────────────────────
        num_posts = pick_range(config["posts_to_read"])
        posts = await browse_and_collect_posts(page, subreddits, num_posts + 5)

        if not posts:
            results["errors"].append("No posts found — possible CAPTCHA or network issue")
            results["success"] = False
            print(json.dumps(results, indent=2))
            return results

        num_upvotes = pick_range(config["upvotes"])
        num_downvotes = pick_range(config["downvotes"])
        num_saves = pick_range(config.get("saves", (0, 1)))

        upvotes_done = 0
        downvotes_done = 0
        saves_done = 0
        posts_read = 0

        for i, post in enumerate(posts):
            if posts_read >= num_posts:
                break
            
            # Every 2-3 posts, browse a feed for a while (like a real user scanning)
            if i > 0 and i % random.randint(2, 3) == 0:
                feed_sub = random.choice(subreddits)
                await browse_feed(page, feed_sub)

            if not await read_post(page, post['url']):
                continue

            posts_read += 1

            if upvotes_done < num_upvotes and random.random() < 0.7:
                if await upvote_post(page):
                    upvotes_done += 1
            elif downvotes_done < num_downvotes and i > 2 and random.random() < 0.2:
                if await downvote_post(page):
                    downvotes_done += 1

            if saves_done < num_saves and random.random() < 0.15:
                if await save_post(page):
                    saves_done += 1

            # Realistic delay between posts (10-30s — like deciding what to click next)
            await human_delay(10, 30)

        results["posts_read"] = posts_read
        results["upvotes"] = upvotes_done
        results["downvotes"] = downvotes_done
        results["saves"] = saves_done

        # ── Targeted comments (Phase 2+ only) ───────────────────────────
        if comment_plan and phase >= 2:
            plan = list(comment_plan)
            random.shuffle(plan)

            max_comments = pick_range(config["comments"]) if isinstance(config["comments"], tuple) else config["comments"]
            plan = plan[:max_comments]

            top_level_ratio = config.get("top_level_ratio", 0.4)

            comments_to_verify = []  # Track posted comments for removal check

            for entry in plan:
                post_url = entry.get("post_url", "")
                comment_text = entry.get("comment", "").strip()
                is_reply = entry.get("reply_to_comment", random.random() > top_level_ratio)
                target_author = entry.get("reply_to_author", None)  # Match reply to specific comment

                if not post_url or not comment_text:
                    results["comments_skipped"] += 1
                    continue

                # Safety net: reject generic comments
                lower = comment_text.lower()
                generic_phrases = [
                    "this is great", "came here to say this", "solid advice",
                    "this right here", "this is the way", "saving this",
                    "needed this today", "bookmarked", "well said",
                    "highly recommend", "game changer",
                ]
                if any(g in lower for g in generic_phrases):
                    results["comments_skipped"] += 1
                    results["errors"].append(f"Rejected generic comment: '{comment_text[:40]}...'")
                    continue

                try:
                    await page.goto(post_url, wait_until="domcontentloaded", timeout=PAGE_TIMEOUT)

                    if await detect_captcha(page):
                        results["captcha_hit"] = True
                        results["errors"].append("CAPTCHA during commenting — aborting")
                        break

                    await human_delay(3, 6)
                    await human_scroll(page, random.randint(2, 4))
                    await human_delay(2, 4)

                    if is_reply:
                        success = await reply_to_comment(page, comment_text, target_author=target_author)
                    else:
                        success = await post_top_level_comment(page, comment_text)

                    if success:
                        comment_record = {
                            "post_url": post_url,
                            "text": comment_text,
                            "type": "reply" if is_reply else "top_level",
                            "subreddit": entry.get("subreddit", ""),
                            "verified": None,  # Will be checked later
                        }
                        results["comments_posted"].append(comment_record)
                        comments_to_verify.append(post_url)
                        await human_delay(8, 15)
                    else:
                        results["comments_skipped"] += 1
                        results["errors"].append(f"Failed to post comment on {post_url}")

                except Exception as e:
                    results["comments_skipped"] += 1
                    results["errors"].append(f"Comment error: {str(e)[:100]}")

                # Stagger between comments (45-90s for premium — slower, more natural)
                await human_delay(45, 90)

            # Verify comments weren't auto-removed (spot check — pick up to 2)
            if comments_to_verify:
                verify_sample = random.sample(comments_to_verify, min(2, len(comments_to_verify)))
                for vurl in verify_sample:
                    await human_delay(10, 20)  # Wait before checking
                    is_visible = await verify_comment_posted(page, vurl, username)
                    if not is_visible:
                        results["errors"].append(f"COMMENT POSSIBLY REMOVED on {vurl}")
                        results["removed_comments"] = results.get("removed_comments", 0) + 1

        # Final homepage scroll
        try:
            await page.goto("https://www.reddit.com/", wait_until="domcontentloaded", timeout=PAGE_TIMEOUT)
            await human_scroll(page, random.randint(2, 4))
        except:
            pass

        # ── Idle phase ───────────────────────────────────────────────────
        active_elapsed = (time.time() - session_start) / 60
        results["active_minutes"] = round(active_elapsed, 1)

        idle_target = max(0, TOTAL_SESSION_SECONDS - (time.time() - session_start))
        if idle_target > 0:
            idle_mins = round(idle_target / 60, 1)
            print(f"[idle] Active phase done ({active_elapsed:.1f} min). Idling {idle_mins} min...", file=sys.stderr)
            idle_start = time.time()
            while (time.time() - idle_start) < idle_target:
                await asyncio.sleep(min(60, idle_target - (time.time() - idle_start)))
            results["idle_minutes"] = round((time.time() - idle_start) / 60, 1)

    except Exception as e:
        results["errors"].append(str(e))
        results["success"] = False
    finally:
        try:
            if bw is not None:
                results["bandwidth"] = bw.summary()
        except:
            pass
        if pw:
            await pw.stop()

    print(json.dumps(results, indent=2))
    return results


# ─── Entry Point ─────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python3 warm-premium.py <cdp_url> <username> <phase> --subreddits 'sub1,sub2,...' [--comment-plan /path.json]")
        sys.exit(1)

    cdp_url = sys.argv[1]
    username = sys.argv[2]
    phase = int(sys.argv[3])

    subreddits = []
    if "--subreddits" in sys.argv:
        idx = sys.argv.index("--subreddits")
        if idx + 1 < len(sys.argv):
            subreddits = [s.strip() for s in sys.argv[idx + 1].split(",")]

    if not subreddits:
        print(json.dumps({"success": False, "error": "No subreddits provided — premium accounts must target historical subs"}))
        sys.exit(1)

    comment_plan = None
    if "--comment-plan" in sys.argv:
        idx = sys.argv.index("--comment-plan")
        if idx + 1 < len(sys.argv):
            try:
                with open(sys.argv[idx + 1]) as f:
                    comment_plan = json.load(f)
                if not isinstance(comment_plan, list):
                    print(json.dumps({"success": False, "error": "Comment plan must be a JSON array"}))
                    sys.exit(1)
            except Exception as e:
                print(json.dumps({"success": False, "error": f"Failed to load comment plan: {e}"}))
                sys.exit(1)

    if phase not in PHASE_CONFIG:
        print(json.dumps({"success": False, "error": f"Invalid phase: {phase}. Must be 1-3."}))
        sys.exit(1)

    asyncio.run(run_premium_warming(cdp_url, username, phase, subreddits, comment_plan))
