#!/usr/bin/env python3
"""
Weekly Top 50 Pain Points → Notion Database (with App Ideation)
Pulls the top 50 pain points (by uncapped viralScore) from MongoDB,
generates app ideation for each via Claude, creates a Notion database
matching the original format.
"""

import json
import time
import urllib.request
from datetime import datetime, timezone
from pymongo import MongoClient

# === Config ===
import os
MONGO_URI = os.environ.get('MONGO_URI', '')
if not MONGO_URI:
    # Load from .env
    env_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '.env')
    if os.path.exists(env_path):
        for line in open(env_path):
            if line.startswith('MONGO_URI='):
                MONGO_URI = line.strip().split('=', 1)[1]
NOTION_SECRET = "REDACTED_NOTION"
PARENT_PAGE_ID = "31b66005-ab52-800d-9c49-fbc517921ae3"
NOTION_VERSION = "2022-06-28"
NOTION_BASE = "https://api.notion.com/v1"

# App ideation: now handled by the cron agent, not direct API calls
# The script outputs pain points as JSON; the agent generates ideation inline

NOTION_HEADERS = {
    "Authorization": f"Bearer {NOTION_SECRET}",
    "Notion-Version": NOTION_VERSION,
    "Content-Type": "application/json",
}

def notion_request(method, endpoint, data=None):
    url = f"{NOTION_BASE}{endpoint}"
    body = json.dumps(data).encode() if data else None
    req = urllib.request.Request(url, data=body, headers=NOTION_HEADERS, method=method)
    try:
        with urllib.request.urlopen(req) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        err = e.read().decode()
        print(f"NOTION ERROR {e.code}: {err[:300]}")
        raise

def load_ideation_cache():
    """Load pre-generated ideation from the cache file if it exists."""
    import os
    cache_path = os.path.expanduser("~/.openclaw/workspace/BRAIN/scrapes/ideation-cache.json")
    try:
        with open(cache_path) as f:
            return json.load(f)
    except Exception:
        return {}

def generate_app_ideation(pain_point_title, description, subreddit, source_posts):
    """Stub: ideation is now generated by the cron agent, not this script.
    Returns a placeholder that the agent will fill in."""
    return {
        "app_idea": f"[Pending ideation for: {pain_point_title[:80]}]",
        "what_it_does": "",
        "how_it_solves": "",
        "feature_set": "",
        "wabi_fit": None,
        "analysis": "Ideation pending — will be filled by cron agent"
    }


def main():
    now = datetime.now(timezone.utc)
    week_label = now.strftime("%B %d, %Y")

    # === Step 1: Pull top 50 from MongoDB ===
    print("Connecting to MongoDB...")
    client = MongoClient(MONGO_URI, serverSelectionTimeoutMS=15000)
    db = client['reddit_scanner']

    top50 = list(db['pain_points'].find(
        {'painPointType': {'$in': ['actionable', None]}}
    ).sort('viralScore', -1).limit(50))

    print(f"Got {len(top50)} pain points")

    # Pre-load linked posts
    pp_ids = [pp['_id'] for pp in top50]
    all_posts = list(db['pain_point_posts'].find({'painPointId': {'$in': pp_ids}}))
    posts_by_pp = {}
    for post in all_posts:
        pid = post['painPointId']
        if pid not in posts_by_pp:
            posts_by_pp[pid] = []
        posts_by_pp[pid].append(post)

    client.close()

    # === Step 2: Load ideation from cache (generated by cron agent) ===
    print("Loading ideation cache...")
    ideation_cache = load_ideation_cache()
    ideations = {}
    for pp in top50:
        pp_id = pp['_id']
        # Try cache by title (agent-generated)
        title = pp.get('title', '')
        cached = ideation_cache.get(str(pp_id)) or ideation_cache.get(title)
        if cached:
            ideations[pp_id] = cached
        else:
            ideations[pp_id] = generate_app_ideation(
                title,
                pp.get('description', ''),
                pp.get('subreddit', ''),
                posts_by_pp.get(pp_id, [])
            )

    cached_count = sum(1 for v in ideations.values() if v.get('wabi_fit') is not None)
    print(f"Loaded {cached_count}/50 ideations from cache, {50-cached_count} pending")

    # Save pain points to JSON for agent-based ideation
    import os
    scrapes_dir = os.path.expanduser("~/.openclaw/workspace/BRAIN/scrapes")
    os.makedirs(scrapes_dir, exist_ok=True)
    pp_export = []
    for pp in top50:
        pp_id = pp['_id']
        posts = posts_by_pp.get(pp_id, [])
        pp_export.append({
            "id": str(pp_id),
            "title": pp.get('title', ''),
            "description": pp.get('description', ''),
            "subreddit": pp.get('subreddit', ''),
            "viralScore": pp.get('viralScore', 0),
            "posts": [{"title": p.get('postTitle', ''), "upvotes": p.get('upvotes', 0)} for p in posts[:3]]
        })
    export_path = os.path.join(scrapes_dir, "weekly-top50-painpoints.json")
    with open(export_path, "w") as f:
        json.dump(pp_export, f, indent=2, default=str)
    print(f"Exported pain points to {export_path}")

    # === Step 3: Create Notion database ===
    title = f"🎯 Top 50 Pain Points — Week of {week_label}"
    print(f"Creating Notion database: {title}")

    db_payload = {
        "parent": {"type": "page_id", "page_id": PARENT_PAGE_ID},
        "title": [{"type": "text", "text": {"content": title}}],
        "properties": {
            "Pain Point": {"title": {}},
            "Subreddit": {"rich_text": {}},
            "Viral Score": {"number": {"format": "number"}},
            "Wabi Fit (1-5)": {"number": {"format": "number"}},
            "App Idea": {"rich_text": {}},
            "What It Does": {"rich_text": {}},
            "How It Solves the Pain": {"rich_text": {}},
            "Feature Set": {"rich_text": {}},
            "Analysis": {"rich_text": {}},
            "Post": {"rich_text": {}},
        }
    }

    db_result = notion_request("POST", "/databases", db_payload)
    db_id = db_result["id"]
    print(f"Database created: {db_id}")

    # === Step 4: Add rows ===
    print(f"Adding {len(top50)} rows...")

    for i, pp in enumerate(top50):
        pp_id = pp['_id']
        posts = posts_by_pp.get(pp_id, [])
        idea = ideations.get(pp_id) or {}

        # Best source post URL
        best_post_url = ""
        if posts:
            best = max(posts, key=lambda p: p.get('upvotes', 0))
            best_post_url = best.get('redditUrl', '')

        def rt(text, max_len=2000):
            """Make a rich_text field, truncated to Notion's limit."""
            t = (text or '')[:max_len]
            return {"rich_text": [{"text": {"content": t}}]} if t else {"rich_text": []}

        properties = {
            "Pain Point": {"title": [{"text": {"content": (pp.get('title') or '')[:200]}}]},
            "Subreddit": rt(pp.get('subreddit', '')),
            "Viral Score": {"number": pp.get('viralScore', 0)},
            "Wabi Fit (1-5)": {"number": idea.get('wabi_fit') if idea else None},
            "App Idea": rt(idea.get('app_idea', '')),
            "What It Does": rt(idea.get('what_it_does', '')),
            "How It Solves the Pain": rt(idea.get('how_it_solves', '')),
            "Feature Set": rt(idea.get('feature_set', '')),
            "Analysis": rt(idea.get('analysis', '')),
            "Post": rt(best_post_url),
        }

        payload = {"parent": {"database_id": db_id}, "properties": properties}

        try:
            notion_request("POST", "/pages", payload)
            print(f"  [{i+1}/50] ✓ {pp.get('title', '?')[:55]}")
        except Exception as e:
            print(f"  [{i+1}/50] ✗ {pp.get('title', '?')[:55]} — {e}")
            time.sleep(2)
            try:
                notion_request("POST", "/pages", payload)
                print(f"  [{i+1}/50] ✓ RETRY OK")
            except Exception as e2:
                print(f"  [{i+1}/50] ✗ RETRY FAILED — {e2}")

        # Rate limit: pause every 3 rows
        if (i + 1) % 3 == 0:
            time.sleep(0.5)

    print(f"\n✅ Done! Database: {title}")
    print(f"   Notion ID: {db_id}")
    print(f"   View at: https://notion.so/{db_id.replace('-', '')}")


if __name__ == '__main__':
    main()
